api_version: v1

platform:
  name: databricks-platform
  version: "1.0"

aws:

  accounts:

    dev:
      account_id: "556940913059"
      environment: dev

      regions:

        us-east-1:
          approved: true

          networks:

            primary:
              name: databricks-dev
              vpc:
                ownership: existing
                id: vpc-PLACEHOLDER

                cidr: 10.20.0.0/16

              subnets:

                private:
                  ownership: terraform

                  allocation:
                    count: 2

                    availability_zones:
                      - us-east-1a
                      - us-east-1b

                    cidr_source: platform

              routing:
                ownership: existing

              security_groups:
                ownership: terraform

              endpoints:
                ownership: existing

              dns:
                ownership: existing
                private_dns: true