variable "databricks_workspace_url" {
  description = "URL of the Databricks workspace"
  type        = string
}

variable "databricks_profile" {
  description = "Databricks CLI profile used to authenticate to the workspace"
  type        = string
  sensitive   = true
}

variable "project_name" {
  description = "Name used to identify resources"
  type        = string
  default     = "databricks-poc"
}

variable "data_bucket_name" {
  description = "S3 bucket used for Databricks Unity Catalog data"
  type        = string
}

variable "databricks_data_access_role_arn" {
  description = "IAM role ARN used by the Unity Catalog storage credential"
  type        = string
}

variable "unity_catalog_external_id" {
  description = "External ID generated by the Databricks Unity Catalog storage credential"
  type        = string
  sensitive   = true
}